### ISSUE TITLE
iemo-test-5-drz.json not found

### ISSUE THREAD

**Issue by wenjie-p** [W-Wu/sTEER#2]
Thanks for your work. I am recently trying to reproduce the experiment, but could not find how to generate iemo-test-5-drz.json file as required in line 111 of Train.py. Could you please tell me how to generate this file?

**Comment by W-Wu** [comment]
Thanks for catching that! The file 'iemo-test-5-drz.json' is generated based on the diarisation results after running step 3 of Testing and scoring (https://github.com/W-Wu/sTEER?tab=readme-ov-file#testing-and-scoring). I've added a file (data_prep/rttm2json.py) as an example to generate this.

**Comment by wenjie-p** [comment]
Thanks for the reply. Actually, this file is required in the Train.py as shown below. 
```python
datasets['fwd_drz'] = sb.dataio.dataset.DynamicItemDataset.from_json(
                 json_path=hparams["fwd_drz_annotation"],
                dynamic_items=[fwd_drz_pipeline],
                output_keys=["id", "sig"],
            )
```
Does it mean this file should not be used in the training stage?

**Comment by W-Wu** [comment]
That's true. "fwd_drz_annotation" is not required during training. FWD_VAD and FWD_DRZ are set to False (by default) during training. I've updated Train.py so that datasets['fwd_drz'] will not be created when FWD_DRZ  is set to False.

**Comment by wenjie-p** [comment]
Hi Wen, thanks for the quick response. I have found another issue that both `label_encoder_emo.txt` and `label_encoder_asr.txt` are missing during the data preparation. Can you check this? Thanks !

**Comment by W-Wu** [comment]
Both of them were already provided in the data/ folder.

**Comment by wenjie-p** [comment]
Oh yes!
