### ISSUE TITLE
Missing raw .wav datafiles for iemocap

### ISSUE THREAD

**Issue by RItesh-47** [W-Wu/sTEER#3]
Hey! I am trying to reproduce this work but the raw iemocap .wav files are missing(required in data_prep/single_channel.py). Can u please provide these datafiles? Thank you.

**Comment by W-Wu** [comment]
Thanks for the comments. The IEMOCAP dataset is license-protected. Please download it from https://sail.usc.edu/iemocap/ and replace iemo_root with the actual data path.
